CREATE TABLE transactions (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    account_id          BIGINT        NOT NULL,
    category_id         BIGINT,
    user_id             BIGINT        NOT NULL,
    amount              DECIMAL(15,2) NOT NULL,
    currency            VARCHAR(3)    NOT NULL,
    converted_amount    DECIMAL(15,2),
    transaction_type    ENUM('INCOME', 'EXPENSE', 'TRANSFER') NOT NULL,
    merchant            VARCHAR(200),
    description         VARCHAR(500),
    transaction_date    DATE          NOT NULL,
    is_recurring        BOOLEAN       NOT NULL DEFAULT FALSE,
    recurring_group_id  BIGINT,
    is_auto_categorized BOOLEAN       NOT NULL DEFAULT FALSE,
    tags                JSON,
    receipt_url         VARCHAR(500),
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_txn_user_date (user_id, transaction_date),
    INDEX idx_txn_account (account_id, transaction_date),
    INDEX idx_txn_category (user_id, category_id, transaction_date),
    INDEX idx_txn_type (user_id, transaction_type, transaction_date),
    INDEX idx_txn_merchant (user_id, merchant(50)),
    FULLTEXT idx_txn_search (merchant, description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
